/-
Copyright (c) 2026 Bryan Sanchez. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bryan Sanchez
-/
import JacobianChallenge.Manifold.C3PeriodLatticeStokesRefactored

set_option linter.unusedSectionVars false

/-! # Further refactoring: `homologyGeneration` from a "spans H₁" hypothesis

`C3PeriodLatticeStokesInputs basis` (in `C3PeriodLatticeStokesRefactored.lean`)
carries `homologyGeneration` as an existential predicate:

  `∀ γ, ∃ n b, b ∈ stokes.boundaries ∧ γ = (∑ n i • cycleGens i) + b`.

This file factors that predicate through the cleaner **textbook
statement**: the quotient `H₁(X; ℤ) := SmoothCycle / boundaries` is
ℤ-generated by the projections of `cycleGens`.

Concretely, in `StokesBoundaryInvariance.H1` (the quotient
`SmoothCycle 𝓘(ℝ, ℂ) X ⧸ stokes.boundaries`), the `ℤ`-submodule spanned
by `stokes.proj ∘ cycleGens` equals `⊤`. Equivalently, every quotient
class is a ℤ-combination of the cycleGens classes.

The derivation of `homologyGeneration` from `H1_spans_top`:
* Project `γ` to `S.H1` via `S.proj`.
* By `H1_spans_top`, `S.proj γ ∈ Submodule.span ℤ (range (S.proj ∘ cycleGens)) = ⊤`.
* Extract a ℤ-combination `S.proj γ = ∑ n i • S.proj (cycleGens i)` via
  the cleaner pattern of `Submodule.mem_span_range_iff_exists_fun`.
* Pulling back through `S.proj`'s additivity:
  `S.proj (γ - ∑ n i • cycleGens i) = 0`, i.e.,
  `γ - ∑ n i • cycleGens i ∈ S.boundaries` (the kernel of `S.proj`).
* Let `b := γ - ∑ n i • cycleGens i`; then `γ = (∑ n i • cycleGens i) + b`
  and `b ∈ stokes.boundaries`.

## Significance

`H1_spans_top` is the **cleanest formal statement** of the classical
content "H₁(X; ℤ) is ℤ-generated by the symplectic basis". Combined
with the existing Stokes bundle, this completes the structural
decomposition of the Period Lattice Construction into atomic textbook
inputs.

## What this file ships

* `C3PeriodLatticeStokesSpanTopInputs basis` — refactored data
  structure with `H1_spans_top` in place of `homologyGeneration`.
* `homologyGeneration_of_spans_top` — derivation lemma.
* `C3PeriodLatticeStokesSpanTopInputs.toStokes` — projection to
  `C3PeriodLatticeStokesInputs basis`.
* `C3PeriodLatticeStokesSpanTopInputs.toClassical` — full chain to
  the unrefactored `C3PeriodLatticeClassicalInputs basis`.
* `C3PeriodLatticeStokesSpanTopInputs.toBundle` — convenience.

No `sorry`, no `axiom`. -/

noncomputable section

open scoped Manifold ContDiff
open Module Submodule

namespace JacobianChallenge

variable {X : Type*} [TopologicalSpace X] [ChartedSpace ℂ X]
  [IsManifold 𝓘(ℂ, ℂ) ω X]

/-- **Period-lattice classical inputs with H₁ generation as a
"spans top" statement.** Same as `C3PeriodLatticeStokesInputs` except
the `homologyGeneration` field is replaced by the cleaner
`H1_spans_top`: the `ℤ`-submodule of `S.H1` spanned by
`stokes.proj ∘ cycleGens` is the entire group.

Geometrically this is the classical fact "`H₁(X; ℤ)` is ℤ-generated by
the symplectic homology basis representatives," with no further
projection-or-existence wrapping. -/
structure C3PeriodLatticeStokesSpanTopInputs
    (basis : Basis (Fin (JacobianChallenge.genus X)) ℂ (HolomorphicOneForm X))
    where
  /-- Tuple of `2g` smooth cycle generators (symplectic homology basis). -/
  cycleGens :
    Fin (2 * JacobianChallenge.genus X) → (PeriodPairingData.ofSmoothCycle X).H1
  /-- Riemann bilinear non-degeneracy: the `2g` period vectors are
  ℝ-linearly independent. -/
  riemannBilinear :
    LinearIndependent ℝ
      (fun i : Fin (2 * JacobianChallenge.genus X) =>
        periodVector (PeriodPairingData.ofSmoothCycle X) basis (cycleGens i))
  /-- Stokes-boundary-invariance data (chosen subgroup of boundaries +
  chosen submodule of closed real 1-forms + vanishing hypothesis). -/
  stokes : StokesBoundaryInvariance 𝓘(ℝ, ℂ) X
  /-- Every holomorphic 1-form is Stokes-closed. -/
  holomorphic_closed :
    ∀ om : HolomorphicOneForm X, om ∈ stokes.closedHolomorphicForms
  /-- **`H₁ is ℤ-generated by the symplectic basis classes`.** The
  `ℤ`-submodule of `stokes.H1` spanned by the images of `cycleGens`
  under the quotient projection equals the entire group. -/
  H1_spans_top :
    (Submodule.span ℤ
      (Set.range (fun i : Fin (2 * JacobianChallenge.genus X) =>
        (stokes.proj (cycleGens i) : stokes.H1)))) = ⊤

namespace C3PeriodLatticeStokesSpanTopInputs

variable
    {basis : Basis (Fin (JacobianChallenge.genus X)) ℂ (HolomorphicOneForm X)}
    (inputs : C3PeriodLatticeStokesSpanTopInputs basis)

/-- **Derivation of `homologyGeneration` from `H1_spans_top`.** Every
smooth cycle differs from a ℤ-combination of `cycleGens` by an element
of `stokes.boundaries`. -/
lemma homologyGeneration_of_spans_top
    (γ : (PeriodPairingData.ofSmoothCycle X).H1) :
    ∃ (n : Fin (2 * JacobianChallenge.genus X) → ℤ)
      (b : (PeriodPairingData.ofSmoothCycle X).H1),
      b ∈ inputs.stokes.boundaries ∧
        γ = (∑ i, n i • inputs.cycleGens i) + b := by
  -- The projection of γ lies in the spanned-top submodule.
  have h_mem :
      (inputs.stokes.proj γ : inputs.stokes.H1) ∈
        Submodule.span ℤ (Set.range (fun i : Fin (2 * JacobianChallenge.genus X) =>
          (inputs.stokes.proj (inputs.cycleGens i) : inputs.stokes.H1))) := by
    rw [inputs.H1_spans_top]; trivial
  -- Extract a finsupp giving the linear combination on the projection side.
  obtain ⟨c, h_proj_eq⟩ :=
    (Finsupp.mem_span_range_iff_exists_finsupp).mp h_mem
  -- The finsupp has finite support; extend to a total function
  -- Fin (2g) → ℤ via `c.toFun` (zero outside support, equal to `c` on
  -- support).
  classical
  let n : Fin (2 * JacobianChallenge.genus X) → ℤ := fun i => c i
  -- The Finsupp.sum equals the Finset.univ.sum since the support is
  -- contained in Finset.univ (Fin is Fintype).
  have h_finsupp_sum :
      c.sum (fun i k => k • (inputs.stokes.proj (inputs.cycleGens i) :
            inputs.stokes.H1)) =
        ∑ i, n i • (inputs.stokes.proj (inputs.cycleGens i) :
            inputs.stokes.H1) := by
    rw [Finsupp.sum_of_support_subset c (Finset.subset_univ _)
      (fun i k => k • (inputs.stokes.proj (inputs.cycleGens i) :
        inputs.stokes.H1))
      (fun i _ => zero_smul ℤ _)]
  -- So `S.proj γ = ∑ n i • S.proj (cycleGens i) = S.proj (∑ n i • cycleGens i)`.
  have h_proj_sum :
      (inputs.stokes.proj γ : inputs.stokes.H1) =
        inputs.stokes.proj (∑ i, n i • inputs.cycleGens i) := by
    rw [← h_proj_eq, h_finsupp_sum, map_sum]
    refine Finset.sum_congr rfl (fun i _ => ?_)
    exact (map_zsmul inputs.stokes.proj (n i) (inputs.cycleGens i)).symm
  -- So `S.proj (γ - ∑ n i • cycleGens i) = 0`.
  have h_proj_zero :
      inputs.stokes.proj (γ - ∑ i, n i • inputs.cycleGens i) =
        (0 : inputs.stokes.H1) := by
    have h_sub_eq :
        inputs.stokes.proj (γ - ∑ i, n i • inputs.cycleGens i) =
          inputs.stokes.proj γ -
            inputs.stokes.proj (∑ i, n i • inputs.cycleGens i) :=
      map_sub inputs.stokes.proj _ _
    rw [h_sub_eq, ← h_proj_sum, sub_self]
  -- Use the `QuotientAddGroup.eq_zero_iff` idiom: `S.proj x = mk x`, so
  -- `mk x = 0 ↔ x ∈ boundaries`.
  have h_b_mem :
      γ - (∑ i, n i • inputs.cycleGens i) ∈ inputs.stokes.boundaries := by
    have h_mk_zero :
        (QuotientAddGroup.mk (γ - ∑ i, n i • inputs.cycleGens i) :
            inputs.stokes.H1) = 0 := h_proj_zero
    rwa [QuotientAddGroup.eq_zero_iff] at h_mk_zero
  refine ⟨n, γ - (∑ i, n i • inputs.cycleGens i), h_b_mem, ?_⟩
  abel

/-- **Conversion to `C3PeriodLatticeStokesInputs`.** -/
noncomputable def toStokes :
    C3PeriodLatticeStokesInputs basis where
  cycleGens := inputs.cycleGens
  riemannBilinear := inputs.riemannBilinear
  stokes := inputs.stokes
  holomorphic_closed := inputs.holomorphic_closed
  homologyGeneration := inputs.homologyGeneration_of_spans_top

/-- **Conversion to `C3PeriodLatticeClassicalInputs`.** -/
noncomputable def toClassical : C3PeriodLatticeClassicalInputs basis :=
  inputs.toStokes.toClassical

/-- **Convenience composition to `PeriodLatticeSymplecticBundle`.** -/
noncomputable def toBundle :
    PeriodLatticeSymplecticBundle (PeriodPairingData.ofSmoothCycle X) basis :=
  inputs.toStokes.toBundle

end C3PeriodLatticeStokesSpanTopInputs

end JacobianChallenge

end
