/-
Copyright (c) 2026 Bryan Sanchez. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bryan Sanchez
-/
import JacobianChallenge.Manifold.ChartLocalPrimitiveMaxConvexBallChartAt
import JacobianChallenge.Manifold.ConvexBallChartAtMaximalAtlas

set_option linter.unusedSectionVars false

/-! # Étale space of `ω`-primitives over `X`

First file of the étale-space arc (Alt B of `AUDIT_LOOP_PERIOD_VANISHES.md`).
Defines the étale space `EtalePrimitives om` of germs of local primitives
of a holomorphic 1-form `om` on a compact connected complex 1-manifold `X`,
together with its étale topology and the base-point projection
`proj : EtalePrimitives om → X`.

## Topology

The carrier is `{(x, c) : X × ℂ}`. The topology is generated by the
chart-local *sheets* — graphs of `chartLocalPrimitiveMax (convexBallChartAt y)`
shifted by an additive constant `c_off`:

```
basicSheet om y V c_off
  := { (x, chartLocalPrimitiveMax (convexBallChartAt y) … om x … + c_off) | x ∈ V }
```

for `y : X`, `V ⊆ (convexBallChartAt y).source` open, and `c_off : ℂ`.

Each basic sheet is the graph of a smooth function `x ↦ F_y(x) + c_off` on
an open subset of a chart ball. Continuity of `proj` follows directly: the
preimage of an open `U ⊆ X` is covered by basic sheets `basicSheet om x' V_x' c'`
for each `(x', c') ∈ U × ℂ`, with `V_x' := U ∩ (convexBallChartAt x').source`
and `c_off := c'` (via `chartLocalPrimitiveMax_self`).

## What this file ships

* `EtalePrimitives om` — the structure `{point : X, primValue : ℂ}`.
* `chartSection om y c_off` — the local section `x ↦ (x, F_y(x) + c_off)`.
* `basicSheet`, `basicSheets`, `instTopologicalSpace` — the étale topology
  generated by chart-local sheets.
* `proj om : EtalePrimitives om → X` — projection to the base, `.point`.
* `continuous_proj` — projection is continuous.

The local-homeomorph / covering-map properties are deferred to the next
chip in the arc. No `sorry`, no `axiom`. -/

noncomputable section

open scoped Manifold Topology ContDiff
open Set

namespace JacobianChallenge

universe u

variable {X : Type u} [TopologicalSpace X] [ChartedSpace ℂ X]
  [IsManifold (𝓘(ℂ, ℂ)) ⊤ X]

/-- **The étale space of `ω`-primitives over `X`.** Carrier: pairs
`(point, primValue)` with `point : X` and `primValue : ℂ` a candidate value
of a local primitive of `ω` at `point`. -/
@[ext]
structure EtalePrimitives (_om : HolomorphicOneForm X) : Type u where
  /-- Base point in `X`. -/
  point : X
  /-- Candidate primitive value at `point`. -/
  primValue : ℂ

namespace EtalePrimitives

variable {om : HolomorphicOneForm X}

/-- **The chart-local section** through `(x, F_y(x) + c_off)` parameterised
by chart-ball center `y : X` and additive offset `c_off : ℂ`. Defined on
the chart-ball source at `y`. -/
noncomputable def chartSection (om : HolomorphicOneForm X) (y : X) (c_off : ℂ)
    (x : X) (hx : x ∈ (convexBallChartAt y).source) : EtalePrimitives om :=
  { point := x
    primValue := chartLocalPrimitiveMax (convexBallChartAt y)
                   (convexBallChartAt_mem_maximalAtlas_real y)
                   (convexBallChartAt_target_convex y) y
                   (convexBallChartAt_x_mem_source y) om x hx + c_off }

@[simp] lemma chartSection_point (om : HolomorphicOneForm X) (y : X) (c_off : ℂ)
    (x : X) (hx : x ∈ (convexBallChartAt y).source) :
    (chartSection om y c_off x hx).point = x := rfl

@[simp] lemma chartSection_primValue (om : HolomorphicOneForm X) (y : X) (c_off : ℂ)
    (x : X) (hx : x ∈ (convexBallChartAt y).source) :
    (chartSection om y c_off x hx).primValue =
      chartLocalPrimitiveMax (convexBallChartAt y)
        (convexBallChartAt_mem_maximalAtlas_real y)
        (convexBallChartAt_target_convex y) y
        (convexBallChartAt_x_mem_source y) om x hx + c_off := rfl

/-- **Self-section identity.** At the chart-ball center `y` itself, the
local section value is the offset alone (since the chart-local primitive
vanishes at its basepoint by `chartLocalPrimitiveMax_self`). -/
@[simp] lemma chartSection_self (om : HolomorphicOneForm X) (y : X) (c_off : ℂ) :
    chartSection om y c_off y (convexBallChartAt_x_mem_source y) =
      ⟨y, c_off⟩ := by
  ext
  · rfl
  · simp [chartSection, chartLocalPrimitiveMax_self]

/-- **A basic sheet of the étale topology.** Image of an open subset `V`
of `(convexBallChartAt y).source` under `chartSection om y c_off`.
Concretely: `{(x, F_y(x) + c_off) | x ∈ V}`. -/
def basicSheet (om : HolomorphicOneForm X) (y : X) (V : Set X)
    (hV_sub : V ⊆ (convexBallChartAt y).source) (c_off : ℂ) :
    Set (EtalePrimitives om) :=
  { e | ∃ x : X, ∃ hxV : x ∈ V, e = chartSection om y c_off x (hV_sub hxV) }

lemma mem_basicSheet_iff (om : HolomorphicOneForm X) (y : X) (V : Set X)
    (hV_sub : V ⊆ (convexBallChartAt y).source) (c_off : ℂ)
    (e : EtalePrimitives om) :
    e ∈ basicSheet om y V hV_sub c_off ↔
      ∃ x : X, ∃ hxV : x ∈ V,
        e = chartSection om y c_off x (hV_sub hxV) := Iff.rfl

/-- **Self-membership of the basic sheet at `(y, c_off)`.** The point
`⟨y, c_off⟩ : EtalePrimitives om` lies in every basic sheet at `y`
whose `V` contains `y` (with offset `c_off`). -/
lemma self_mem_basicSheet (om : HolomorphicOneForm X) (y : X) (V : Set X)
    (hV_sub : V ⊆ (convexBallChartAt y).source) (hy : y ∈ V) (c_off : ℂ) :
    (⟨y, c_off⟩ : EtalePrimitives om) ∈ basicSheet om y V hV_sub c_off := by
  refine ⟨y, hy, ?_⟩
  rw [chartSection_self]

/-- **Every basic sheet projects into its `V` parameter.** Image of a
basic sheet under `.point` is contained in `V`. -/
lemma basicSheet_point_mem (om : HolomorphicOneForm X) (y : X) (V : Set X)
    (hV_sub : V ⊆ (convexBallChartAt y).source) (c_off : ℂ)
    {e : EtalePrimitives om} (he : e ∈ basicSheet om y V hV_sub c_off) :
    e.point ∈ V := by
  obtain ⟨x, hxV, h_eq⟩ := he
  rw [h_eq, chartSection_point]
  exact hxV

/-- **Every basic sheet at `(y, c_off)` has every member of the form
`(x, F_y(x) + c_off)`.** Specifically: for `e ∈ basicSheet`, the primValue
is determined by the point and the offset via `chartLocalPrimitiveMax`. -/
lemma basicSheet_primValue_eq (om : HolomorphicOneForm X) (y : X) (V : Set X)
    (hV_sub : V ⊆ (convexBallChartAt y).source) (c_off : ℂ)
    {e : EtalePrimitives om} (he : e ∈ basicSheet om y V hV_sub c_off) :
    e.primValue =
      chartLocalPrimitiveMax (convexBallChartAt y)
        (convexBallChartAt_mem_maximalAtlas_real y)
        (convexBallChartAt_target_convex y) y
        (convexBallChartAt_x_mem_source y) om e.point
        (hV_sub (basicSheet_point_mem om y V hV_sub c_off he)) + c_off := by
  obtain ⟨x, hxV, h_eq⟩ := he
  subst h_eq
  rfl

/-- **The collection of basic sheets** indexed by `(y, V, c_off)` with `V`
open and contained in the chart-ball source at `y`. -/
def basicSheets (om : HolomorphicOneForm X) : Set (Set (EtalePrimitives om)) :=
  { S | ∃ y : X, ∃ V : Set X, IsOpen V ∧
        ∃ hV_sub : V ⊆ (convexBallChartAt y).source, ∃ c_off : ℂ,
        S = basicSheet om y V hV_sub c_off }

/-- **The étale topology on `EtalePrimitives om`.** Generated by the
chart-local sheets. -/
instance instTopologicalSpace (om : HolomorphicOneForm X) :
    TopologicalSpace (EtalePrimitives om) :=
  TopologicalSpace.generateFrom (basicSheets om)

/-- A basic sheet is open in the étale topology. -/
lemma basicSheet_isOpen (om : HolomorphicOneForm X) (y : X) (V : Set X)
    (hV_open : IsOpen V) (hV_sub : V ⊆ (convexBallChartAt y).source)
    (c_off : ℂ) :
    IsOpen (basicSheet om y V hV_sub c_off) := by
  apply TopologicalSpace.GenerateOpen.basic
  exact ⟨y, V, hV_open, hV_sub, c_off, rfl⟩

/-- **Projection to the base.** -/
def proj (om : HolomorphicOneForm X) : EtalePrimitives om → X := fun e => e.point

@[simp] lemma proj_apply (om : HolomorphicOneForm X) (e : EtalePrimitives om) :
    proj om e = e.point := rfl

@[simp] lemma proj_mk (om : HolomorphicOneForm X) (x : X) (c : ℂ) :
    proj om ⟨x, c⟩ = x := rfl

@[simp] lemma proj_chartSection (om : HolomorphicOneForm X) (y : X) (c_off : ℂ)
    (x : X) (hx : x ∈ (convexBallChartAt y).source) :
    proj om (chartSection om y c_off x hx) = x := rfl

/-- **Projection is continuous.** Preimage of an open `U ⊆ X` is a union
of basic sheets, one through each `(x', c') : U × ℂ`. -/
lemma continuous_proj (om : HolomorphicOneForm X) : Continuous (proj om) := by
  rw [continuous_def]
  intro U hU
  -- Show `proj om ⁻¹' U` is open in the étale topology.
  -- For each `e ∈ proj om ⁻¹' U`, exhibit an open basic sheet through `e`
  -- contained in the preimage.
  rw [isOpen_iff_forall_mem_open]
  intro e he
  -- `he : e.point ∈ U`.
  have he_point : e.point ∈ U := he
  -- Sub-chart-ball at `e.point`.
  set V : Set X := U ∩ (convexBallChartAt e.point).source with hV_def
  have hV_open : IsOpen V :=
    hU.inter (convexBallChartAt e.point).open_source
  have hV_sub : V ⊆ (convexBallChartAt e.point).source := inter_subset_right
  have he_point_inV : e.point ∈ V :=
    ⟨he_point, convexBallChartAt_x_mem_source e.point⟩
  -- The basic sheet at `(e.point, V, e.primValue)` contains `e`.
  refine ⟨basicSheet om e.point V hV_sub e.primValue, ?_, ?_, ?_⟩
  · -- Sheet ⊆ preimage of U.
    intro e' he'
    have : e'.point ∈ V := basicSheet_point_mem _ _ _ _ _ he'
    exact this.1
  · exact basicSheet_isOpen om e.point V hV_open hV_sub e.primValue
  · -- e ∈ sheet (witness: x = e.point, hxV = he_point_inV).
    refine ⟨e.point, he_point_inV, ?_⟩
    ext
    · rfl
    · simp [chartSection, chartLocalPrimitiveMax_self]

end EtalePrimitives

end JacobianChallenge

end
