/-
Copyright (c) 2026 Bryan Sanchez. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bryan Sanchez
-/
import JacobianChallenge.Manifold.C3PeriodLatticeStokesCanonical
import JacobianChallenge.Manifold.C3PeriodLatticeStokesNonemptyHeadline
import JacobianChallenge.Manifold.HolomorphicComponentsCanonicalClosed

set_option linter.unusedSectionVars false

/-! # `GenericGenusPeriodLatticeInputs`: the 4 atomic canonical-bundle inputs for general genus

For general `X : Type*` (compact connected complex 1-manifold) and a
`ℂ`-basis `α` of `HolomorphicOneForm X` of dimension `g = genus X`, the
period-lattice closure on `X` reduces (via the canonical Stokes bundle
and the existing structural reductions) to **four atomic classical
inputs**:

1. **`cycleGens`** — a tuple of `2g` smooth 1-cycles representing a
   symplectic homology basis of `H₁(X; ℤ)`.

2. **`riemannBilinear`** — ℝ-linear independence of the `2g` period
   vectors `α ↦ ∫_{γᵢ} αⱼ` (the Hodge bilinear non-degeneracy on a
   compact Riemann surface).

3. **`holomorphicCanonicalClosed`** — real and imaginary components of
   every holomorphic 1-form integrate to zero around every smooth
   2-simplex boundary (Stokes' theorem applied to `dω = 0` for
   holomorphic ω).

4. **`H1_spans_top_canonical`** — the canonical Stokes H₁ quotient
   `SmoothCycle / stokesBoundaries` is ℤ-generated by the projections
   of `cycleGens` (cellular-homology generation on a compact
   topological surface of genus `g`).

For genus 0 (X with `Subsingleton (HolomorphicOneForm X)`, e.g.,
`RiemannSphere`) all four are unconditional in tree.

For genus ≥ 1, each is genuinely-new classical content not at the
mathlib pin:
* (1) `cycleGens` — Surface classification + a choice of basis cycles.
* (2) `riemannBilinear` — Hodge theory / Riemann bilinear relations.
* (3) `holomorphicCanonicalClosed` — Stokes' theorem on smooth
  2-simplices + Cauchy-Riemann ⟹ `dω = 0` for holomorphic ω.
* (4) `H1_spans_top_canonical` — Cellular / singular homology of
  a compact orientable 2-manifold.

## What this file ships

* `GenericGenusPeriodLatticeInputs X basis` — a structure bundling
  the four atomic inputs.
* `GenericGenusPeriodLatticeInputs.toBundle` — promotes to a
  `C3PeriodLatticeStokesSpanTopInputs basis` via
  `C3PeriodLatticeStokesSpanTopInputs.ofCanonical`.
* `nonempty_C3PeriodLatticeStokesSpanTopInputs_of_genericGenus` —
  `Nonempty (GenericGenusPeriodLatticeInputs X basis) → Nonempty
  (C3PeriodLatticeStokesSpanTopInputs basis)`.
* `nonempty_periodLatticeSymplecticBundle_of_genericGenus` — composes
  the above with `Nonempty.periodLatticeSymplecticBundle_of_stokesSpanTop`.

No `sorry`, no `axiom`. -/

open scoped Manifold ContDiff
open Module Submodule

namespace JacobianChallenge

variable {X : Type*} [TopologicalSpace X] [ChartedSpace ℂ X]
  [IsManifold 𝓘(ℂ, ℂ) ω X]

/-- **The four atomic canonical-bundle inputs for general genus.**

For general `X` and a `ℂ`-basis `α` of `HolomorphicOneForm X`, this
type bundles the four classical-content inputs that suffice (via the
canonical Stokes bundle) to give `Nonempty
(C3PeriodLatticeStokesSpanTopInputs basis)` and hence
`Nonempty (PeriodLatticeSymplecticBundle data basis)`. -/
structure GenericGenusPeriodLatticeInputs
    (basis : Basis (Fin (JacobianChallenge.genus X)) ℂ (HolomorphicOneForm X))
    where
  /-- Tuple of `2g` smooth cycle generators (symplectic homology basis). -/
  cycleGens :
    Fin (2 * JacobianChallenge.genus X) → (PeriodPairingData.ofSmoothCycle X).H1
  /-- Riemann bilinear non-degeneracy: the `2g` period vectors are
  ℝ-linearly independent. -/
  riemannBilinear :
    LinearIndependent ℝ
      (fun i : Fin (2 * JacobianChallenge.genus X) =>
        periodVector (PeriodPairingData.ofSmoothCycle X) basis (cycleGens i))
  /-- Real and imaginary components of every holomorphic 1-form lie in
  the canonical closed-forms subgroup. -/
  holomorphicCanonicalClosed :
    ∀ om : HolomorphicOneForm X,
      realComponent om ∈ canonicalClosedForms 𝓘(ℝ, ℂ) X ∧
      imagComponent om ∈ canonicalClosedForms 𝓘(ℝ, ℂ) X
  /-- The canonical Stokes H₁ quotient is ℤ-spanned by the symplectic
  basis classes. -/
  H1_spans_top_canonical :
    (Submodule.span ℤ
      (Set.range (fun i : Fin (2 * JacobianChallenge.genus X) =>
        ((StokesBoundaryInvariance.canonical 𝓘(ℝ, ℂ) X).proj (cycleGens i) :
          (StokesBoundaryInvariance.canonical 𝓘(ℝ, ℂ) X).H1)))) = ⊤

namespace GenericGenusPeriodLatticeInputs

variable {basis : Basis (Fin (JacobianChallenge.genus X)) ℂ (HolomorphicOneForm X)}

/-- **Promote to `C3PeriodLatticeStokesSpanTopInputs basis`** via the
canonical-bundle constructor. -/
noncomputable def toBundle
    (inputs : GenericGenusPeriodLatticeInputs basis) :
    C3PeriodLatticeStokesSpanTopInputs basis :=
  C3PeriodLatticeStokesSpanTopInputs.ofCanonical basis
    inputs.cycleGens inputs.riemannBilinear
    inputs.holomorphicCanonicalClosed inputs.H1_spans_top_canonical

end GenericGenusPeriodLatticeInputs

/-- **`Nonempty GenericGenusPeriodLatticeInputs → Nonempty
C3PeriodLatticeStokesSpanTopInputs`.** -/
theorem nonempty_C3PeriodLatticeStokesSpanTopInputs_of_genericGenus
    (basis : Basis (Fin (JacobianChallenge.genus X)) ℂ (HolomorphicOneForm X))
    (h : Nonempty (GenericGenusPeriodLatticeInputs basis)) :
    Nonempty (C3PeriodLatticeStokesSpanTopInputs basis) :=
  h.map GenericGenusPeriodLatticeInputs.toBundle

/-- **Headline: `Nonempty GenericGenusPeriodLatticeInputs → Nonempty
PeriodLatticeSymplecticBundle`.** -/
theorem nonempty_periodLatticeSymplecticBundle_of_genericGenus
    (basis : Basis (Fin (JacobianChallenge.genus X)) ℂ (HolomorphicOneForm X))
    (h : Nonempty (GenericGenusPeriodLatticeInputs basis)) :
    Nonempty
      (PeriodLatticeSymplecticBundle (PeriodPairingData.ofSmoothCycle X) basis) :=
  letI : Nonempty (C3PeriodLatticeStokesSpanTopInputs basis) :=
    nonempty_C3PeriodLatticeStokesSpanTopInputs_of_genericGenus basis h
  Nonempty.periodLatticeSymplecticBundle_of_stokesSpanTop basis

end JacobianChallenge
