/-
Copyright (c) 2026 Bryan Sanchez. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bryan Sanchez
-/
import JacobianChallenge.Manifold.HodgeFiniteDimensional
import JacobianChallenge.Manifold.RiemannSphere
import JacobianChallenge.Manifold.RiemannSphereGenus

set_option diagnostics.threshold 100

/-! # `HolomorphicOneFormFiniteDim` for the Riemann sphere

This file is the first instance of ZZ76's named hypothesis
`JacobianChallenge.HolomorphicOneFormFiniteDim X` being supplied for a
concrete `X`, namely the Riemann sphere `RiemannSphere = OnePoint ℂ`.

## Honest content

The deep input — `Subsingleton (HolomorphicOneForm RiemannSphere)` — is
**still open** in this repository (see `RiemannSphereGenus.lean`'s
`HolomorphicOneForm_RiemannSphere_subsingleton_statement`). This file does
*not* close that gap. What it provides is the bridge:

```
Subsingleton (HolomorphicOneForm RiemannSphere)
  → HolomorphicOneFormFiniteDim RiemannSphere
```

i.e. once the analytic chart-coefficient chase from `RiemannSphereGenus.lean`
is completed and produces the `Subsingleton` instance, the
finite-dimensionality hypothesis ZZ76 carries is discharged for free. This
is the linear-algebra side of the genus-zero argument; everything else
upstream (Hodge theory, elliptic regularity) is unnecessary for this
specific manifold because the space of holomorphic 1-forms is the **zero**
subspace, not just finite-dimensional.

## What is proven (no `sorry`, no `axiom`)

* `Module.Finite.of_subsingleton` (local) — any `Subsingleton`
  `R`-module is `Module.Finite` (the empty set spans, since every element
  is forced to `0`).
* `holomorphicOneFormFiniteDim_riemannSphere_of_subsingleton` — the bridge
  named above.
* `holomorphicOneFormFiniteDim_riemannSphere_of_subsingleton_statement` —
  the same bridge, taking the `Prop`-form
  `HolomorphicOneForm_RiemannSphere_subsingleton_statement` from
  `RiemannSphereGenus.lean` as input. This is the form most convenient for
  downstream callers that thread the `_statement` props rather than
  `Subsingleton` instances.

## What is **not** proven here

* `holomorphicOneFormFiniteDim_riemannSphere :
    HolomorphicOneFormFiniteDim RiemannSphere` — unconditional. Closing
  this requires the open `Subsingleton (HolomorphicOneForm RiemannSphere)`
  instance from `RiemannSphereGenus.lean`'s docstring sketch (the
  chart-coefficient + Liouville chase). The unconditional theorem is
  recorded as `Prop`-only in `holomorphicOneFormFiniteDim_riemannSphere_statement`
  with the deliberate `_statement` suffix flagging it as still owed.
-/

open scoped Manifold Topology

noncomputable section

namespace JacobianChallenge

namespace RiemannSphere

/-! ### `Module.Finite` from `Subsingleton`

A subsingleton `R`-module is finitely generated by the empty set: every
element is forced to be `0`, hence lies in the span of `∅`. Mathlib has
this fact in various guises; we provide a self-contained proof to keep
this file's mathlib-API surface narrow. -/

/-- Any subsingleton module is `Module.Finite`. The empty set spans because
every element is `0`. -/
private lemma moduleFinite_of_subsingleton
    (R : Type*) [Semiring R] (M : Type*) [AddCommMonoid M] [Module R M]
    [Subsingleton M] : Module.Finite R M := by
  refine ⟨⟨(∅ : Finset M), ?_⟩⟩
  -- Every element of `M` is `0` (by subsingleton), and `0 ∈ ⊤.span = ⊥.span = ⊥ ⊆ ...`.
  -- It suffices to show `⊤ ≤ Submodule.span R (∅ : Finset M)`.
  rw [Finset.coe_empty, Submodule.span_empty]
  intro x _
  -- `x = 0` because `M` is a subsingleton.
  have hx : x = 0 := Subsingleton.elim x 0
  rw [hx]
  exact Submodule.zero_mem _

/-! ### The conditional bridge -/

/-- **Conditional discharge of ZZ76's hypothesis for the Riemann sphere.**

If the space of global holomorphic 1-forms on the Riemann sphere is a
subsingleton (the still-open deep input from `RiemannSphereGenus.lean`),
then ZZ76's named hypothesis
`JacobianChallenge.HolomorphicOneFormFiniteDim RiemannSphere` holds.

This is honest content: a one-step linear-algebra reduction from the open
analytic input to ZZ76's hypothesis. Closing the analytic input would, via
this bridge, immediately discharge the hypothesis without invoking any
Hodge / elliptic machinery — appropriate for the sphere because the
geometric genus is `0`. -/
theorem holomorphicOneFormFiniteDim_riemannSphere_of_subsingleton
    (h : Subsingleton (HolomorphicOneForm RiemannSphere)) :
    JacobianChallenge.HolomorphicOneFormFiniteDim RiemannSphere := by
  haveI := h
  -- `HolomorphicOneFormFiniteDim X` unfolds to `Module.Finite ℂ (HolomorphicOneForm X)`.
  exact moduleFinite_of_subsingleton ℂ (HolomorphicOneForm RiemannSphere)

/-- The same bridge, accepting the `Prop`-form
`HolomorphicOneForm_RiemannSphere_subsingleton_statement` from
`RiemannSphereGenus.lean`. -/
theorem holomorphicOneFormFiniteDim_riemannSphere_of_subsingleton_statement
    (h : HolomorphicOneForm_RiemannSphere_subsingleton_statement) :
    JacobianChallenge.HolomorphicOneFormFiniteDim RiemannSphere :=
  holomorphicOneFormFiniteDim_riemannSphere_of_subsingleton h

/-! ### The unconditional statement, recorded as `Prop`-only

The `_statement` suffix is the same flagging convention used by
`RiemannSphereGenus.lean` for content that is asserted but not yet proven.
Closing this reduces (via the bridge above) to closing
`HolomorphicOneForm_RiemannSphere_subsingleton_statement`. -/

/-- **Open.** ZZ76's named hypothesis specialised to the Riemann sphere.
Reduces to `HolomorphicOneForm_RiemannSphere_subsingleton_statement` via
`holomorphicOneFormFiniteDim_riemannSphere_of_subsingleton_statement`. -/
def holomorphicOneFormFiniteDim_riemannSphere_statement : Prop :=
  JacobianChallenge.HolomorphicOneFormFiniteDim RiemannSphere

/-- The bridge from the open `Subsingleton`-form `Prop` to the open
`HolomorphicOneFormFiniteDim`-form `Prop`. -/
theorem holomorphicOneFormFiniteDim_riemannSphere_statement_of_subsingleton_statement
    (h : HolomorphicOneForm_RiemannSphere_subsingleton_statement) :
    holomorphicOneFormFiniteDim_riemannSphere_statement :=
  holomorphicOneFormFiniteDim_riemannSphere_of_subsingleton_statement h

end RiemannSphere

end JacobianChallenge

end
