/-
Copyright (c) 2026 Bryan Sanchez. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bryan Sanchez
-/
import JacobianChallenge.Manifold.MeromorphicDegreeFiberSum
import JacobianChallenge.Manifold.ZeroCountEqPoleCount
import JacobianChallenge.Divisor.PrincipalDivisorRange

set_option diagnostics true
set_option diagnostics.threshold 100

/-! # Cross-equivalence Iffs for the residue-theorem reformulations

Three independent reformulations of the residue theorem
`(principalDivisorMap f).degree = 0` are landed in this repository,
each under a different name and shape:

1. **Fibre-sum integers** — `MeromorphicDegreeFiberSum`'s
   `degree_eq_zero_iff_meromorphicDegrees_eq`:

       `(principalDivisorMap f).degree = 0
          ↔ meromorphicDegreeAtZero f = meromorphicDegreeAtInfty f`.

   This is the integer-side shadow of "the two generic fibres of
   `f̃ : X → S²` over `0` and `∞` have equal multiplicity-weighted
   cardinality".

2. **Topological-degree bundle** — `ZeroCountEqPoleCount`'s
   `tdfb_iff_principalDegree_zero`:

       `TopologicalDegreeFibreBalance_hypothesis f
          ↔ (principalDivisorMap f).degree = 0`.

   This is the bundle-shaped Route-B hypothesis: a structure with one
   named gap `zero_eq_pole : zeroCount f = poleCount f`.

3. **Subgroup-inclusion** — `PrincipalDivisorRange`'s
   `residueTheorem_iff_range_le_Div0`:

       `ResidueTheorem X ↔ PrincDivHonestCandidate X ≤ Div0 X`.

   This is the global form: "every principal divisor has degree zero"
   ⇔ "the additive subgroup generated by principal divisors lands in
   the degree-zero subgroup".

This file picks reformulations (1) and (2) and adds the **direct
cross-equivalence Iffs** between them — both per-`f` and globally —
so a future agent who closes any *one* of these reformulations
automatically closes both. The Iffs go through the existing
per-`f` equivalences with `(principalDivisorMap f).degree = 0`
(`degree_eq_zero_iff_meromorphicDegrees_eq` and
`tdfb_iff_principalDegree_zero`), which are themselves proven via
the decomposition lemma `signedMult_eq_zeroCount_sub_poleCount`.

We also add the global cross-equivalence to the subgroup-inclusion
form (3), tying all three reformulations into a single equivalence
class at the global level.

## What is real-proof here

* `meromorphicDegrees_eq_iff_topologicalDegreeFibreBalance`
  — per-`f` Iff between the fibre-integer equality and the bundle.
* `forall_meromorphicDegrees_eq_iff_residueTheorem`
  — global form for the fibre-integer equality.
* `forall_meromorphicDegrees_eq_iff_topologicalDegreeFibreBalance`
  — global form chaining (1) with (2).
* `forall_meromorphicDegrees_eq_iff_range_le_Div0`
  — global form chaining (1) with the subgroup-inclusion (3).

## Honest framing

* No `axiom`, no `sorry`.
* No signature change, no `Basic.lean` modification.
* The Iffs are not `Iff.rfl` in general — each goes through one
  small bookkeeping rewrite (typically `sub_eq_zero` already absorbed
  into the per-`f` equivalences). What this file *does* is expose
  the cross-equivalences directly, without forcing the caller to
  manually compose two existing Iffs each time.
* This file does **not** discharge the residue theorem. It is a
  *renaming* layer: the four named statements
  `meromorphicDegrees_eq`, `TopologicalDegreeFibreBalance_hypothesis`,
  `(principalDivisorMap _).degree = 0`, and the subgroup inclusion
  `PrincDivHonestCandidate X ≤ Div0 X` are all the same `Prop`
  modulo small bookkeeping. -/

noncomputable section

open scoped Manifold Topology ContDiff BigOperators

namespace JacobianChallenge

namespace MeromorphicDegreeFiberSum

universe u

variable {X : Type u}
  [TopologicalSpace X] [T2Space X] [CompactSpace X] [ConnectedSpace X]
  [ChartedSpace ℂ X] [IsManifold (𝓘(ℂ, ℂ)) ω X]

/-! ## Per-`f` cross-equivalence: fibre-integers ↔ topological-degree bundle -/

/-- **Per-`f` cross-equivalence (proven).**

The fibre-integer equality
`meromorphicDegreeAtZero f = meromorphicDegreeAtInfty f`
and the Route-B bundle
`TopologicalDegreeFibreBalance_hypothesis f`
are `Iff`-equivalent.

Proof: chain
`degree_eq_zero_iff_meromorphicDegrees_eq` (this namespace)
with `tdfb_iff_principalDegree_zero` (in
`ResidueViaTopologicalDegree`), both pivoting on
`(principalDivisorMap f).degree = 0`. -/
lemma meromorphicDegrees_eq_iff_topologicalDegreeFibreBalance
    (f : MeromorphicNonzero X) :
    meromorphicDegreeAtZero f = meromorphicDegreeAtInfty f
      ↔ JacobianChallenge.ResidueViaTopologicalDegree.TopologicalDegreeFibreBalance_hypothesis f :=
  (degree_eq_zero_iff_meromorphicDegrees_eq f).symm.trans
    (JacobianChallenge.ResidueViaTopologicalDegree.tdfb_iff_principalDegree_zero f).symm

/-! ## Global cross-equivalences -/

/-- **Global equivalence with `ResidueTheorem X` (proven).**

`(∀ f, meromorphicDegreeAtZero f = meromorphicDegreeAtInfty f)` and
`JacobianChallenge.ResidueTheorem X` are `Iff`-equivalent. The
forward direction is the existing
`ResidueTheorem_holds_of_meromorphicDegrees_eq`; the reverse direction
applies the per-`f` Iff to each `f`. -/
lemma forall_meromorphicDegrees_eq_iff_residueTheorem :
    (∀ f : MeromorphicNonzero X,
        meromorphicDegreeAtZero f = meromorphicDegreeAtInfty f)
      ↔ JacobianChallenge.ResidueTheorem X :=
  ⟨ResidueTheorem_holds_of_meromorphicDegrees_eq,
    fun hRT f => meromorphicDegrees_eq_of_degree_zero (hRT f)⟩

/-- **Global cross-equivalence: fibre-integers ↔ topological-degree bundle.**

`(∀ f, meromorphicDegreeAtZero f = meromorphicDegreeAtInfty f)` and
`(∀ f, TopologicalDegreeFibreBalance_hypothesis f)` are
`Iff`-equivalent. Chains
`forall_meromorphicDegrees_eq_iff_residueTheorem` with
`forall_tdfb_iff_residueTheorem` (both proven). -/
lemma forall_meromorphicDegrees_eq_iff_topologicalDegreeFibreBalance :
    (∀ f : MeromorphicNonzero X,
        meromorphicDegreeAtZero f = meromorphicDegreeAtInfty f)
      ↔ (∀ f : MeromorphicNonzero X,
          JacobianChallenge.ResidueViaTopologicalDegree.TopologicalDegreeFibreBalance_hypothesis f) :=
  forall_meromorphicDegrees_eq_iff_residueTheorem.trans
    (JacobianChallenge.ResidueViaTopologicalDegree.forall_tdfb_iff_residueTheorem).symm

/-- **Global cross-equivalence: fibre-integers ↔ subgroup-inclusion.**

`(∀ f, meromorphicDegreeAtZero f = meromorphicDegreeAtInfty f)` and
`PrincDivHonestCandidate X ≤ Div0 X` are `Iff`-equivalent. Chains
`forall_meromorphicDegrees_eq_iff_residueTheorem` with
`residueTheorem_iff_range_le_Div0` (both proven).

This is the bridge from the integer-side fibre formulation to the
divisor-side subgroup formulation. Discharging either one closes the
other automatically. -/
lemma forall_meromorphicDegrees_eq_iff_range_le_Div0 :
    (∀ f : MeromorphicNonzero X,
        meromorphicDegreeAtZero f = meromorphicDegreeAtInfty f)
      ↔ JacobianChallenge.PrincDivHonestCandidate X ≤ JacobianChallenge.Div0 X :=
  forall_meromorphicDegrees_eq_iff_residueTheorem.trans
    JacobianChallenge.residueTheorem_iff_range_le_Div0

/-! ## Honest summary

The four named statements

* `∀ f, meromorphicDegreeAtZero f = meromorphicDegreeAtInfty f`
  (fibre-integer reformulation, this namespace)
* `∀ f, TopologicalDegreeFibreBalance_hypothesis f`
  (topological-degree bundle, `ResidueViaTopologicalDegree`)
* `JacobianChallenge.ResidueTheorem X`
  (divisor-degree zero, `Divisor.PrincipalDivisorRange`)
* `JacobianChallenge.PrincDivHonestCandidate X ≤ JacobianChallenge.Div0 X`
  (subgroup inclusion, `Divisor.PrincipalDivisorRange`)

are pairwise `Iff`-equivalent. Two of those equivalences are already
landed (`forall_tdfb_iff_residueTheorem` and
`residueTheorem_iff_range_le_Div0`); this file adds the missing
direct cross-equivalences with the fibre-integer form, so a future
agent need not manually compose two existing Iffs to move between
any pair of the four reformulations.

**No discharge.** The four are the residue theorem in four guises.
A real proof requires either branched-covering theory (Route A) or
`d log f` Stokes (Route B). The point of this Iff infrastructure is
to prevent an agent from "sharpening" one route while ignoring its
equivalence to the others. -/

end MeromorphicDegreeFiberSum

end JacobianChallenge

end
