/-
Copyright (c) 2026 Bryan Sanchez. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bryan Sanchez
-/
import JacobianChallenge.Manifold.ComplexPeriodSmulRight
import JacobianChallenge.Manifold.PeriodPairingDefinition

set_option diagnostics.threshold 100

/-! # `PeriodPairingData X` from smooth-cycle infrastructure

The smooth-chain arc (PL-1 → PL-3f) culminates in
`complexPeriodBilinear : SmoothCycle 𝓘(ℝ, ℂ) X →+ HolomorphicOneForm X
→ₗ[ℂ] ℂ`. Its signature is exactly `data.H1 →+
(HolomorphicOneForm X →ₗ[ℂ] ℂ)` for the `PeriodPairingData X` bundle
in `PeriodPairingDefinition.lean`, with `data.H1 := SmoothCycle 𝓘(ℝ, ℂ) X`.

This chip packages that observation: it constructs the canonical
`PeriodPairingData X` term whose `H1` carrier is the smooth-cycle group
and whose pairing is `complexPeriodBilinear`. The result is a
**concrete, unconditional** `PeriodPairingData X` — the previous bridge
chips left `data` abstract.

## Caveat: cycles vs. true H₁

`SmoothCycle I X` is the kernel of `SmoothChain.boundary`, *not* the
homology group `H₁(X; ℤ) = ker boundary / image boundary`. Two cycles
differing by a boundary represent the same homology class but are
distinct as smooth cycles. So the period image
`periodLatticeImage (ofSmoothCycle X) α`
is the additive subgroup generated by periods of *all* smooth cycles,
including those that are boundaries.

Under Stokes (`StokesBoundaryInvariance`, an existing named hypothesis
in `Manifold/H1SmoothMod.lean`), the period of every boundary is zero,
and the smooth-cycle period image agrees with the true H₁ period image.
The full quotient-descended pairing lives in
`Manifold/ComplexPeriodH1.lean` (`complexPeriodH1Bilinear`) and a
downstream chip will provide `PeriodPairingData.ofH1SmoothMod` mirroring
this one but on the descended object.

Even at the current coarseness, `ofSmoothCycle` is genuine
infrastructure: it lets the entire PL-3-fin and PL-4 framework operate
on a concrete `PeriodPairingData X` term rather than an abstract one,
and the downstream Abel-Jacobi map construction can begin against it.

No `sorry`, no `axiom`.
-/

noncomputable section

open scoped Manifold ContDiff

namespace JacobianChallenge

variable (X : Type*) [TopologicalSpace X] [ChartedSpace ℂ X]
  [IsManifold 𝓘(ℂ, ℂ) ⊤ X]

/-- **Canonical `PeriodPairingData X` from smooth cycles.** Uses
`SmoothCycle 𝓘(ℝ, ℂ) X` as the integer homology carrier and
`complexPeriodBilinear` as the pairing. This is the concrete bundle the
PL-3-fin and PL-4 chips work against. -/
def PeriodPairingData.ofSmoothCycle : PeriodPairingData X where
  H1 := SmoothCycle 𝓘(ℝ, ℂ) X
  pairing := complexPeriodBilinear

variable {X}

/-- **Unfold the pairing on a specific cycle / form.** The
`PeriodPairing` value through `ofSmoothCycle` is just the complex
period. -/
lemma PeriodPairing_ofSmoothCycle
    (c : SmoothCycle 𝓘(ℝ, ℂ) X) (om : HolomorphicOneForm X) :
    PeriodPairing (PeriodPairingData.ofSmoothCycle X) c om = complexPeriod c om :=
  rfl

end JacobianChallenge

end
