/-
Copyright (c) 2026 Bryan Sanchez. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Bryan Sanchez
-/
import JacobianChallenge.Manifold.HodgeFiniteDimensional
import JacobianChallenge.Manifold.PeriodPairingDefinition
import JacobianChallenge.Manifold.PeriodLatticeRankTwoG
import Mathlib.LinearAlgebra.Basis.Defs
import Mathlib.LinearAlgebra.Dimension.Finrank

/-! # Period image lattice (chip ZZ85)

Given the named-hypothesis bundle `PeriodPairingData X` (chip ZZ81) and a
chosen `ℂ`-basis `(α₁, …, α_g)` of `HolomorphicOneForm X` of length
`g = genus X`, this file constructs the **period image map**

  `periodImage : data.H1 →+ (Fin (genus X) → ℂ)`,
  `periodImage γ i = PeriodPairing data γ (α_i)`,

and defines the **period image lattice**

  `PeriodImageLattice := AddSubgroup.range periodImage`

as an `AddSubgroup` of `Fin (genus X) → ℂ`. This is the additive subgroup
of `ℂ^g` generated by the period vectors of all integer 1-cycles against
the chosen basis of holomorphic 1-forms — i.e., the *honest* shape of the
period lattice of a compact Riemann surface, with the singular-homology
hypothesis still living inside `data : PeriodPairingData X`.

## Wrapper into `PeriodLatticeOfRankTwoG`

The companion `PeriodLatticeRankTwoG.lean` (chip ZZ77) packages the data
of an honest period lattice as a structure with two further properties:
closedness in `ℂ^g` and free `ℤ`-rank `2 * genus X`. Neither follows from
`PeriodPairingData` alone — closedness requires discreteness of the
period image (a real analytic input) and the rank certificate requires
`H₁(X; ℤ) ≃ ℤ^{2g}` for a compact orientable surface (singular homology
of closed surfaces). We therefore expose the wrapper

  `ofPeriodImage`
    : (data : PeriodPairingData X) → (basis : Fin g → HolomorphicOneForm X)
      → IsClosed (PeriodImageLattice data basis : Set _)
      → Module.finrank ℤ (PeriodImageLattice data basis).toIntSubmodule
            = 2 * genus X
      → PeriodLatticeOfRankTwoG X

as a *Tier-2 reduction*: a strict reader who supplies a pairing bundle, a
basis, a closedness witness, and a rank-`2g` certificate gets a term of
the bundle of chip ZZ77, and thus all the `TopologicalSpace` /
`AddCommGroup` / `T2Space` infrastructure of `JacobianOfLattice X data`
becomes available. The two named hypotheses are deliberately not proved
here — they are exactly the open mathematical content (discreteness of
the period image plus rank-`2g` of `H₁(X; ℤ)`).

## What this file does NOT do

* It does not assert that a closedness witness or a rank-`2g`
  certificate exists. Inhabitation is an open chip.
* It does not pick a canonical basis of `HolomorphicOneForm X`. The
  basis is a parameter, exposed so a downstream chip with
  `HolomorphicOneFormFiniteDim X` in hand can pass
  `Module.Finite.exists_fin` / `Basis.ofFinite` output directly.
* It does not modify any signature in `PeriodPairingDefinition.lean` or
  `PeriodLatticeRankTwoG.lean`. All new content is additive.
-/

open scoped Manifold Topology Bundle ContDiff

noncomputable section

set_option diagnostics.threshold 100

namespace JacobianChallenge

variable (X : Type*) [TopologicalSpace X] [ChartedSpace ℂ X] [IsManifold 𝓘(ℂ) ω X]

/-- The **period image map** as an `AddMonoidHom` from `data.H1` into the
finite product `Fin (genus X) → ℂ`. Given a period-pairing bundle `data`
and a length-`g` family `basis : Fin g → HolomorphicOneForm X` (intended
to be a `ℂ`-basis), the `i`-th component sends a 1-cycle `γ` to the
period of `basis i` over `γ`.

This is a homomorphism of additive groups by additivity of the pairing
in the cycle (`PeriodPairing_add_left`). No hypothesis on `basis` is
needed for this construction — the basis property only enters when one
later wants to compare different choices. -/
def periodImage
    (data : PeriodPairingData X)
    (basis : Fin (JacobianChallenge.genus X) → HolomorphicOneForm X) :
    data.H1 →+ (Fin (JacobianChallenge.genus X) → ℂ) where
  toFun γ := fun i => PeriodPairing data γ (basis i)
  map_zero' := by
    funext i
    exact PeriodPairing_zero_left data (basis i)
  map_add' γ γ' := by
    funext i
    exact PeriodPairing_add_left data γ γ' (basis i)

variable {X}

/-- Coordinate-evaluation of `periodImage`. -/
@[simp]
theorem periodImage_apply
    (data : PeriodPairingData X)
    (basis : Fin (JacobianChallenge.genus X) → HolomorphicOneForm X)
    (γ : data.H1) (i : Fin (JacobianChallenge.genus X)) :
    periodImage X data basis γ i = PeriodPairing data γ (basis i) := rfl

/-- The period at the zero cycle is the zero vector. -/
@[simp]
theorem periodImage_zero
    (data : PeriodPairingData X)
    (basis : Fin (JacobianChallenge.genus X) → HolomorphicOneForm X) :
    periodImage X data basis 0 = 0 :=
  (periodImage X data basis).map_zero

/-- Negation. -/
@[simp]
theorem periodImage_neg
    (data : PeriodPairingData X)
    (basis : Fin (JacobianChallenge.genus X) → HolomorphicOneForm X)
    (γ : data.H1) :
    periodImage X data basis (-γ) = - periodImage X data basis γ :=
  (periodImage X data basis).map_neg γ

/-- Additivity. -/
theorem periodImage_add
    (data : PeriodPairingData X)
    (basis : Fin (JacobianChallenge.genus X) → HolomorphicOneForm X)
    (γ γ' : data.H1) :
    periodImage X data basis (γ + γ') =
      periodImage X data basis γ + periodImage X data basis γ' :=
  (periodImage X data basis).map_add γ γ'

variable (X)

/-- The **period image lattice**: the additive subgroup of `ℂ^g` spanned
by the period vectors `(∫_γ α_1, …, ∫_γ α_g)` over all 1-cycles
`γ : data.H1`, where `α_i = basis i`. Defined as the range of the
`AddMonoidHom` `periodImage`. -/
def PeriodImageLattice
    (data : PeriodPairingData X)
    (basis : Fin (JacobianChallenge.genus X) → HolomorphicOneForm X) :
    AddSubgroup (Fin (JacobianChallenge.genus X) → ℂ) :=
  (periodImage X data basis).range

variable {X}

/-- Membership in the period image lattice unfolds to "is a period
vector of some 1-cycle against the chosen basis". -/
theorem mem_periodImageLattice_iff
    (data : PeriodPairingData X)
    (basis : Fin (JacobianChallenge.genus X) → HolomorphicOneForm X)
    (v : Fin (JacobianChallenge.genus X) → ℂ) :
    v ∈ PeriodImageLattice X data basis ↔
      ∃ γ : data.H1, periodImage X data basis γ = v := by
  simp [PeriodImageLattice, AddMonoidHom.mem_range]

/-- The image of any `γ : data.H1` lies in the period image lattice. -/
theorem periodImage_mem
    (data : PeriodPairingData X)
    (basis : Fin (JacobianChallenge.genus X) → HolomorphicOneForm X)
    (γ : data.H1) :
    periodImage X data basis γ ∈ PeriodImageLattice X data basis :=
  ⟨γ, rfl⟩

/-- The zero vector lies in the period image lattice. -/
theorem zero_mem_periodImageLattice
    (data : PeriodPairingData X)
    (basis : Fin (JacobianChallenge.genus X) → HolomorphicOneForm X) :
    (0 : Fin (JacobianChallenge.genus X) → ℂ) ∈
      PeriodImageLattice X data basis :=
  (PeriodImageLattice X data basis).zero_mem

/-! ### Tier-2 wrapper into `PeriodLatticeOfRankTwoG`

A strict reader who supplies a pairing bundle, a basis of holomorphic
1-forms, a closedness witness for the period image, and a rank-`2g`
certificate gets a term of the bundle from chip ZZ77.
-/

/-- **Tier-2 wrapper.** Promote the period image lattice to a
`PeriodLatticeOfRankTwoG X` bundle, given the two missing pieces of data:

* `hClosed` — closedness of the period image in `ℂ^g`,
* `hRank` — free `ℤ`-rank of the period image is `2 * genus X`.

The first is a real-analytic fact about the period map; the second is the
algebraic-topology input `H₁(X; ℤ) ≃ ℤ^{2g}` for a compact orientable
surface. Neither lives in mathlib at the pin, so they are exposed here as
hypotheses rather than proved. With them in hand, the algebraic and
topological infrastructure of `JacobianOfLattice X _` (chip ZZ77) becomes
unconditionally available. -/
def PeriodLatticeOfRankTwoG.ofPeriodImage
    (data : PeriodPairingData X)
    (basis : Fin (JacobianChallenge.genus X) → HolomorphicOneForm X)
    (hClosed : IsClosed
      ((PeriodImageLattice X data basis :
          Set (Fin (JacobianChallenge.genus X) → ℂ))))
    (hRank :
      Module.finrank ℤ
          ((PeriodImageLattice X data basis).toIntSubmodule)
        = 2 * JacobianChallenge.genus X) :
    PeriodLatticeOfRankTwoG X where
  lattice := PeriodImageLattice X data basis
  lattice_isClosed := hClosed
  lattice_rank_eq := hRank

/-- The lattice carried by `ofPeriodImage` is *literally* the period
image lattice. -/
@[simp]
theorem PeriodLatticeOfRankTwoG.ofPeriodImage_lattice
    (data : PeriodPairingData X)
    (basis : Fin (JacobianChallenge.genus X) → HolomorphicOneForm X)
    (hClosed : IsClosed
      ((PeriodImageLattice X data basis :
          Set (Fin (JacobianChallenge.genus X) → ℂ))))
    (hRank :
      Module.finrank ℤ
          ((PeriodImageLattice X data basis).toIntSubmodule)
        = 2 * JacobianChallenge.genus X) :
    (PeriodLatticeOfRankTwoG.ofPeriodImage data basis hClosed hRank).lattice
      = PeriodImageLattice X data basis := rfl

/-! ### Convenience: extracting a basis from `HolomorphicOneFormFiniteDim`

Under the named hypothesis `HolomorphicOneFormFiniteDim X`, the
`ℂ`-vector space `HolomorphicOneForm X` is finite-dimensional. By
definition `genus X = Module.finrank ℂ (HolomorphicOneForm X)`, so a
basis indexed by `Fin (genus X)` exists. We expose this as a `Prop`-level
existence so downstream chips can `obtain` a basis without tracking
intermediate `FiniteDimensional` instances.
-/

/-- Under finite-dimensionality of `HolomorphicOneForm X`, there exists a
`ℂ`-basis indexed by `Fin (genus X)`. -/
theorem exists_basis_of_HolomorphicOneFormFiniteDim
    (h : HolomorphicOneFormFiniteDim X) :
    ∃ b : Basis (Fin (JacobianChallenge.genus X)) ℂ (HolomorphicOneForm X),
      True := by
  -- `genus X` is by definition `Module.finrank ℂ (HolomorphicOneForm X)`,
  -- and under `h` the space is finite-dimensional, so `finBasis` applies.
  haveI : FiniteDimensional ℂ (HolomorphicOneForm X) :=
    finiteDimensional_of_HolomorphicOneFormFiniteDim h
  refine ⟨?_, trivial⟩
  -- `Module.finBasis ℂ V` produces a basis indexed by `Fin (finrank ℂ V)`
  -- when `V` is finite-dimensional. By definition this matches `genus X`.
  exact Module.finBasis ℂ (HolomorphicOneForm X)

end JacobianChallenge

end
